# Generated by Django 2.1.4 on 2019-03-02 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190302_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Cooperative'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
        ),
    ]
