# Generated by Django 2.1.4 on 2019-05-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
