# Generated by Django 2.1.4 on 2019-03-02 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190302_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Member'),
        ),
    ]
