# Generated by Django 2.1.4 on 2019-03-02 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190302_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author2',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='partner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Member'),
        ),
        migrations.AddField(
            model_name='comment',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
        ),
    ]
