# Generated by Django 2.1.4 on 2019-03-02 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190302_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='member',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='general',
        ),
        migrations.RemoveField(
            model_name='post',
            name='member',
        ),
        migrations.RemoveField(
            model_name='post',
            name='partner',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='coop_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='corporate_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
