# Generated by Django 2.1.4 on 2019-05-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190510_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/static/seek/images/f10.jpg', upload_to='image/'),
        ),
    ]
