# Generated by Django 2.1.4 on 2019-03-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190302_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coop_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='corporate_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
