# Generated by Django 2.1.4 on 2019-06-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(default='Single', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='Miss', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=1),
        ),
    ]
