# Generated by Django 2.1.4 on 2019-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190626_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
    ]
