# Generated by Django 2.1.4 on 2019-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='animal husbandry', max_length=255),
        ),
    ]
