# Generated by Django 2.1.4 on 2019-04-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.URLField(blank=True),
        ),
    ]
