# Generated by Django 2.1.4 on 2019-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190618_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
