# Generated by Django 2.1.4 on 2019-06-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190618_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_status',
            field=models.CharField(default='User', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='author_status',
            field=models.CharField(default='User', max_length=255),
        ),
        migrations.AddField(
            model_name='reply',
            name='author_status',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
