# Generated by Django 2.1.4 on 2019-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190622_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='Agricultural Economics', max_length=255),
        ),
    ]
