# Generated by Django 2.1.4 on 2019-03-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('Area_of_Specialization', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/')),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='document/')),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.Cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField()),
                ('time_of_request', models.DateTimeField()),
                ('date_of_admission', models.DateTimeField(blank=True)),
                ('cooperative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cooperative.Cooperative')),
            ],
        ),
    ]
