# Generated by Django 2.1.4 on 2019-06-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_auto_20190510_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='icon',
            field=models.ImageField(default='/', upload_to='image/'),
        ),
    ]
