# Generated by Django 2.1.4 on 2019-04-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0003_remove_member_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('C', 'Commitee Member'), ('M', 'Member')], default='M', max_length=10),
        ),
    ]
