# Generated by Django 2.1.4 on 2019-06-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0004_auto_20190607_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='time_granted',
            field=models.DateTimeField(blank=True),
        ),
    ]
