# Generated by Django 2.1.4 on 2019-04-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0004_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='motto',
            field=models.CharField(default='', max_length=255),
        ),
    ]
