# Generated by Django 2.1.4 on 2019-04-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0005_cooperative_motto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperative',
            old_name='image',
            new_name='icon',
        ),
    ]
