# Generated by Django 2.1.4 on 2019-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0006_auto_20190612_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='time_granted',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='loan',
            name='time_to_pay',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
