# Generated by Django 2.1.4 on 2019-04-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0006_auto_20190423_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiprequest',
            old_name='cooperative_id',
            new_name='cooperative',
        ),
    ]
