# Generated by Django 2.1.4 on 2019-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0007_auto_20190613_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='time_granted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='time_to_pay',
            field=models.DateTimeField(null=True),
        ),
    ]
