# Generated by Django 2.1.4 on 2019-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0008_cooperative_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='reg_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
