# Generated by Django 2.1.4 on 2019-05-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0009_cooperative_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='bank',
        ),
    ]
