# Generated by Django 2.1.4 on 2019-06-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0009_auto_20190613_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='no_of_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Floor Member', 'Floor Member')], default='Member', max_length=20),
        ),
    ]
