# Generated by Django 2.1.4 on 2019-05-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0010_auto_20190502_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='status',
            field=models.CharField(choices=[('N', 'None'), ('V', 'Verified'), ('U', 'Unverified')], default='N', max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Committee Member', 'Committee Member'), ('Member', 'Member')], default='Member', max_length=10),
        ),
    ]
