# Generated by Django 2.1.4 on 2019-05-03 14:22

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0011_auto_20190502_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=builtins.id, serialize=False, to='cooperative.Member')),
                ('item', models.CharField(choices=[('N', 'None'), ('L', 'Loan'), ('N', 'Need'), ('M', 'Membership'), ('I', 'Investment')], default='N', max_length=20)),
                ('item_id', models.IntegerField()),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
