# Generated by Django 2.1.4 on 2019-06-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0011_auto_20190621_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need',
            old_name='body',
            new_name='purpose',
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='motivation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='need',
            name='mandated_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
