# Generated by Django 2.1.4 on 2019-06-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0012_auto_20190625_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='amount',
        ),
    ]
