# Generated by Django 2.1.4 on 2019-05-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='member',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='granted',
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('G', 'Granted'), ('D', 'Declined')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='verified',
            field=models.BooleanField(default=None),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
