# Generated by Django 2.1.4 on 2019-05-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0013_auto_20190503_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprequest',
            name='status',
        ),
    ]
