# Generated by Django 2.1.4 on 2019-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0013_remove_investment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='business_plan',
            field=models.FileField(default='/', upload_to=''),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='letter',
            field=models.FileField(default='/', upload_to=''),
        ),
    ]
