# Generated by Django 2.1.4 on 2019-06-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0014_auto_20190625_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='reg_no',
        ),
    ]
