# Generated by Django 2.1.4 on 2019-04-17 16:01

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=builtins.id, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(upload_to='image/')),
                ('corporate_name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('specialization', models.CharField(max_length=255)),
                ('website', models.URLField()),
            ],
        ),
    ]
