# Generated by Django 2.1.4 on 2019-04-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='image',
            new_name='banner',
        ),
    ]
