# Generated by Django 2.1.4 on 2019-04-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20190422_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='banner',
            new_name='icon',
        ),
    ]
