# Generated by Django 2.1.4 on 2019-06-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20190622_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='maximum_degree',
            field=models.CharField(default='No Degree', max_length=125),
        ),
    ]
