# Generated by Django 2.1.4 on 2019-03-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20190307_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='institution',
            new_name='specialization',
        ),
    ]
